spring:
  application:
    name:
      "taskServer01"
  datasource:
    url: jdbc:postgresql://localhost:5432/test_server_db
    username: postgres
    password: 8749
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      format_sql: true
